### ISSUE TITLE
Cannot read default value of class method if its a property of instance property

### ISSUE THREAD

**Issue by othree** [arrizalamin/js-function-reflector#13]
Sample code:

```js
const fnr = require('js-function-reflector');

class My {
  constructor () {
    this.options = {
      foo: 'foo',
      bar: 'bar'
    };
  }

  hello (foo = this.options.foo) {
    console.log(foo);
  }
}

fnr(My.prototype.hello);
```

Result:

```
undefined:1
(this.options.foo)
              ^

TypeError: Cannot read property 'foo' of undefined
    at eval (eval at Parser.pushBuffer (/Users/othree/tmp-projects/function-reflector-issue/node_modules/js-function-reflector/argument_parser.js:119:24), <anonymous>:1:15)
    at Parser.pushBuffer (/Users/othree/tmp-projects/function-reflector-issue/node_modules/js-function-reflector/argument_parser.js:119:24)
    at Parser.parse (/Users/othree/tmp-projects/function-reflector-issue/node_modules/js-function-reflector/argument_parser.js:78:14)
    at module.exports (/Users/othree/tmp-projects/function-reflector-issue/node_modules/js-function-reflector/header_parser.js:10:21)
    at reflector (/Users/othree/tmp-projects/function-reflector-issue/node_modules/js-function-reflector/index.js:34:18)
    at Object.<anonymous> (/Users/othree/tmp-projects/function-reflector-issue/index.js:16:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

I don't know what is the expected result of this case.
So I can't send PR, sorry.

**Comment by arrizalamin** [comment]
this package works by parsing source code of a function with `toString()` method. so when parsing parameter with variable `this` as its default value, parser doesn't know what value of `this` because it's outside parser's scope. but from version 1.4.0, you can pass an instance of class `My` as variable `this` to the scope of reflector, for example:
```javascript
const fnr = require('js-function-reflector');

class My {
  constructor () {
    this.options = {
      foo: 'foo',
      bar: 'bar'
    };
  }

  hello (foo = this.options.foo) {
    console.log(foo);
  }
}

fnr.call({ this: new My() }, My.prototype.hello);
```
